version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: itihaas-api
    ports:
      - '8000:8000'
    volumes:
      - .:/app
      - /app/node_modules
    command: ['npm', 'run', 'dev']
